name: Docker Build and Deploy with ORAS

on:
  pull_request:
  push:
    branches: main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build and Push Docker Container with ORAS
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t medical_linac:latest .

      - name: Save Docker Image to Tarball
        run: |
          docker save medical_linac:latest -o medical_linac.tar
          mkdir -p extracted && tar -xvf medical_linac.tar -C extracted
          ls -R extracted  # Check the extracted files

      - name: Log in to GitHub Container Registry using ORAS
        run: echo "${{ secrets.GITHUB_TOKEN }}" | oras login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Install ORAS CLI
        run: |
          curl -sSL https://github.com/oras-project/oras/releases/download/v0.15.0/oras_0.15.0_linux_amd64.tar.gz | tar -xzv oras && sudo mv oras /usr/local/bin/

      - name: Push Docker Image to ORAS registry
        run: |
          # Adjust the following paths based on the output from 'ls -R extracted'
          oras push ghcr.io/${{ github.repository }}:latest-docker \
          extracted/layer.tar:application/vnd.docker.image.rootfs.diff.tar.gzip \
          extracted/config.json:application/vnd.docker.container.image.v1+json
