name: Docker Build and Deploy with ORAS

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build and Push Docker Container with ORAS
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Aggiorna alla versione più recente

      - name: Build Docker Image
        run: |
          docker build -t medical_linac:latest .

      - name: Save Docker Image to Tarball
        run: |
          docker save medical_linac:latest -o medical_linac.tar
          mkdir -p extracted && tar -xvf medical_linac.tar -C extracted
          ls -R extracted  # Check the extracted files

      - name: Install ORAS CLI
        run: |
          curl -sSL https://github.com/oras-project/oras/releases/download/v0.15.0/oras_0.15.0_linux_amd64.tar.gz | tar -xzv oras && sudo mv oras /usr/local/bin/

      - name: Log in to GitHub Container Registry using ORAS
        run: |
          oras login ghcr.io -u ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
          
      - name: Push Docker Image to ORAS registry
        run: |
          oras push ghcr.io/${{ github.repository }}:latest-docker \
          medical_linac.tar:application/vnd.docker.image.rootfs.diff.tar.gzip
